config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :posts, except: [:show]

  mount LetterOpenerWeb::Engine, at: "/emails" if Rails.env.production?
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

      can :read, :all                   # allow everyone to read everything

      if user.has_role? :admin
        can :manage, :all
        can :access, :rails_admin   # grant access to rails_admin
        can :dashboard              # grant access to the dashboard
      else
        can :read, :all
        can :manage, Post, :user_id => user.id
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users

  resourcify

  rails_admin do
    configure :user do
      label 'Author of the post: '
    end
  end

  validates :author, presence: true
  validates :title, presence: true
  validates :body, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy


has_attached_file :avatar,
  :styles => {
    :thumb  => "60x60>",
    :small  => "80x80>",
    :medium => "140x140>",
    :large  => "300x300>"},
  :default_url => "/images/default_avatar_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :avatar) }
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :full_name, :description, :password, :current_password, :password_confirmation, :avatar) }
  end
end

app/controllers/confirmation_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  def new
    super
  end

  def create
    super
  end

  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])

    # if resource.errors.empty?
    #   set_flash_message(:notice, :confirmed) if is_navigational_format?
    #   sign_in(resource_name, resource)
    #   respond_with_navigational(resource){ redirect_to root_path }
    # else
    #   respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render_with_scope :new }
    # end
    if resource.errors.empty?
      set_flash_message(:notice, :confirmed) if is_flashing_format?
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  protected
    # The path used after confirmation.
  def after_confirmation_path_for(resource_name)
    if signed_in?(resource_name)
      signed_in_root_path('/')
    else
      new_session_path(resource_name)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # user_signed_in?, current_user, user_session

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  # def show
  # end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    # @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :index, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path , notice: 'Post was successfully updated.' }
        format.json { render :index, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:author, :title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.posts.each {|post| post.destroy}
    @user.avatar = nil
    @user.save
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Myblog"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" Myblog
          .navbar-collapse.collapse.navbar-responsive-collapse
            -if user_signed_in?
              ul.nav.navbar-nav
                - if can? :access, :rails_admin, current_user
                  li= link_to 'Administration', rails_admin_path, method: :get
              ul.nav.navbar-nav.pull-right
                -if current_user.avatar?
                  li= image_tag current_user.avatar.url(:thumb), class: 'round-image-50'
                - else
                  li= image_tag 'small/missing.png', class: 'round-image-50'
                li= link_to 'Edit Profile', edit_user_registration_path
                li= link_to 'Logout', destroy_user_session_path, :method => :delete
            - elsif Rails.env.production?
              ul.nav.navbar-nav
                li= link_to 'Sent emails', '/emails', method: :get
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

app/views/posts/_form.html.slim
= form_for @post, html: { class: "form form-horizontal post" } do |f|
  .form-group
    = f.label :author, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :author, :class => 'form-control'
    = f.error_span(:author)
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    = f.error_span(:title)
  .form-group
    = f.label :body, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :body, :class => 'form-control'
    = f.error_span(:body)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/posts/edit.html.slim
- model_class = Post
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/index.html.slim
- model_class = Post
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

= link_to t('.new', :default => t("helpers.links.new")), new_post_path, :class => 'btn btn-lg btn-primary'
hr.custom-hr

table.table.table-striped
  tbody
    - @posts.each do |post|
      tr
        td width="150"
          h3 = post.author
        td
          h4 = post.title
          hr.style-three
          = post.body
        td width="100"
          - if can? :update, post
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(post), :class => 'btn btn-default'
          hr.style-three
          - if can? :destroy, post
            = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/posts/new.html.slim
- model_class = Post
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/_form.html.slim
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    = f.error_span(:email)
  .form-group
    = f.label :encrypted_password, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :encrypted_password, :class => 'form-control'
    = f.error_span(:encrypted_password)
  .form-group
    = f.label :reset_password_token, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :reset_password_token, :class => 'form-control'
    = f.error_span(:reset_password_token)
  .form-group
    = f.label :reset_password_sent_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :reset_password_sent_at, :class => 'form-control'
    = f.error_span(:reset_password_sent_at)
  .form-group
    = f.label :remember_created_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :remember_created_at, :class => 'form-control'
    = f.error_span(:remember_created_at)
  .form-group
    = f.label :current_sign_in_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :current_sign_in_at, :class => 'form-control'
    = f.error_span(:current_sign_in_at)
  .form-group
    = f.label :last_sign_in_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_sign_in_at, :class => 'form-control'
    = f.error_span(:last_sign_in_at)
  .form-group
    = f.label :current_sign_in_ip, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :current_sign_in_ip, :class => 'form-control'
    = f.error_span(:current_sign_in_ip)
  .form-group
    = f.label :last_sign_in_ip, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_sign_in_ip, :class => 'form-control'
    = f.error_span(:last_sign_in_ip)
  .form-group
    = f.label :confirmation_token, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :confirmation_token, :class => 'form-control'
    = f.error_span(:confirmation_token)
  .form-group
    = f.label :confirmed_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :confirmed_at, :class => 'form-control'
    = f.error_span(:confirmed_at)
  .form-group
    = f.label :confirmation_sent_at, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :confirmation_sent_at, :class => 'form-control'
    = f.error_span(:confirmation_sent_at)
  .form-group
    = f.label :unconfirmed_email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :unconfirmed_email, :class => 'form-control'
    = f.error_span(:unconfirmed_email)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"